spring:
  config:
    import: application-secret.yml
  web:
    resources:
      add-mappings: false # Disable static resource mapping (For NoHandlerFoundException)
  datasource:
    url: jdbc:mysql://localhost:3306/joonggae?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.hibernate.sql: debug